### ISSUE TITLE
Improve key rotation

### ISSUE THREAD

**Issue by ybelMekk** [nais/digdirator#109]
The key rotation procedures as of now aren't very fault tolerant. There are multiple problems:

1. The self-service API may be down or unavailable. If this happens, we should gracefully fall back to reusing existing keys - this obviously only applies for existing Clients with associated Secrets in the cluster.
2. The keys are eventually consistent within DigDir's systems, which means any new keys may be unrecognized for several minutes after registration. This should be remedied by having a "sliding window" of keys; any previous keys in use by pods, the newest (current) key, and the next key which should be generated and preregistered so that it is ready for the next rotation. 
3. The Secret should be updated (without rotating the keys?) when the configuration (e.g. well-known URLs) have changed, or when the synchronizationHash is unset/cleared. Currently, we only update the Secret when spec.secretName is different than the synchronized secret name in the Status object.
4. The keys expire at DigDir exactly 1 year after registration, noted by the `exp` field in the response from DigDir's APIs. We should automatically trigger rotations when reconciling if the expiry is within a certain threshold, e.g. less than 1 month or so.

**Comment by tronghn** [comment]
Case 1: Wontfix for now. Not much instability lately.

Case 2: DigDir has communicated that the eventually consistent key/client synchronization (i.e. up to 10 minutes) is a result of the parallel operation of old and new platforms, and that this should change when the new self-service APIs are released next year.

Case 3: Already fixed.

Case 4: The expiry of keys at DigDir is still a problem, but we'll address that in a separate issue.
