### ISSUE TITLE
Digdirator trenger KMS tilgang for tenants

### ISSUE THREAD

**Issue by ybelMekk** [nais/digdirator#120]
Digdirator trenger både KMS og Secret Manager tilgang

Disse 2 må lastes opp av en tenant i tillegg må vi få litt informasjonen fra tenant for å sette opp digdirator.

**Comment by jhrv** [comment]
Tenker man her da at man pr. tenant som ønsker digdirator, enabler denne featuren i nais-terraform-modules? Og at man gir en tenant-admin gruppe rettigheter til å styre denne KMS key-ringen?

**Comment by ybelMekk** [comment]
Ja, det er tanken. Virksomhets sertifikat er en delikat ting i staten, så tror nok de må vare en eller annen som har admin tilgang.

men her finns det sikkert bedre løsninger, men syns måten vi har løst digdirator på, at digdirator selv aldrig har tilgang på sertifikater.

dette må nok dokumenteres nøye.

**Comment by frodesundby** [comment]
Bør det være opp til tenant å opprette sitt eget KMS slik at vi slipper sitte med ansvaret for potensielt svært sensitive ting?
Vi kan i såfall heller opprette en serviceaccount for digdirator og beskrive for tenant hvordan de oppretter KMS og gir tilgang til denne serviceaccounten.

**Comment by ybelMekk** [comment]
Jeg skal få lit hjelp av Marcel imorgen. 
Det er han som har satt opp Keyring og import av key (virksomhetssertifikat), så han skal passende nok bytte et av sertifikatene, så kan skal gå igjennom stegene og dele dette med meg.

Då kan jeg dokumentere dette for andre etater som vill ta Digdirator i bruk.

Jeg har denne outline:

* Dokumentere hvordan en tenant får satt opp og lastet opp et sertifikat med riktig type og algorithm
* Hva vi i NAIS trenger for å aktivere dette (key path)
* Hvordan en tenant gir tilgang på Digdirator (Service account trenger tilgang på key, roller for service account setter vi opp)
* Dokumentere hva Digdirator får tilgang på og hvordan dette styres.

**Comment by ybelMekk** [comment]
Legger til teknisk dokumentasjon når ™  gir meg det..
