### ISSUE TITLE
Exposed scope is never nil

### ISSUE THREAD

**Issue by hadrienk** [nais/digdirator#20]
The map returned by the method `GetExposedScopes` is never nil. The test should check `len(exposedScopes) > 0`

https://github.com/nais/digdirator/blob/90ea81994b885828d63016b0d5ee201521cbc1c0/controllers/common/reconciler.go#L179-L186

**Comment by tronghn** [comment]
Thanks, fixed in 4ea24f08cbfcc018c52c431bb8ec62c49894e9ab.
